### ISSUE TITLE
Is there a problem with the last two download links？

### ISSUE THREAD

**Issue by akajking** [Yejin0111/AICITY2022-Track1-MTMC#5]
I can't find the following files：
SCMT/dataspace/AICITY_test/
├── aic22_1_test_infer_v2_Convnext.pkl
├── aic22_1_test_infer_v2_HR48_eps.pkl
├── aic22_1_test_infer_v2_R50.pkl
├── aic22_1_test_infer_v2_Res2Net200.pkl
├── aic22_1_test_infer_v2_ResNext101.pkl
├── gen_detection_feat.py

**Comment by Yejin0111** [comment]
Hi, please download these pickle files from [this link](https://pan.baidu.com/s/1Qc5rE6OkMaW8vHg-SDdBew), (The password is **0vcw**) and then put them in this folder.

**Comment by akajking** [comment]
The structure of this download file is
├── c04*.pkl # ReID features. * indicates 1 to 6
├── c04*.txt # Tracking results. * indicates 1 to 6
├── c04*_truncation.pkl # truncation rates. * indicates 1 to 6
not
├── aic22_1_test_infer_v2_Convnext.pkl
├── aic22_1_test_infer_v2_HR48_eps.pkl
├── aic22_1_test_infer_v2_R50.pkl
├── aic22_1_test_infer_v2_Res2Net200.pkl
├── aic22_1_test_infer_v2_ResNext101.pkl

I can't find the following files：
SCMT/dataspace/AICITY_test/
├── aic22_1_test_infer_v2_Convnext.pkl
├── aic22_1_test_infer_v2_HR48_eps.pkl
├── aic22_1_test_infer_v2_R50.pkl
├── aic22_1_test_infer_v2_Res2Net200.pkl
├── aic22_1_test_infer_v2_ResNext101.pkl
├── gen_detection_feat.py

**Comment by troylujc** [comment]
Oh, it's probably a mistake we made. The correct download links are updated in README. Sorry for the inconvenience.

**Comment by akajking** [comment]
Thank you very much！Good luck！

**Comment by LamnouarMohamed** [comment]
Hi,

Thank you for sharing this repository, and I have tried to download your results but I didn't success car restriction of Baidu (if you need to create account inside it you need number phone for check it) because I am not Chinese 

Thank you
